name: Gradle Packaging
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
      fail-fast: false
    name: ${{ matrix.os }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          java-version: 24
          distribution: temurin
      - name: Print JAVA_HOME
        run: echo $JAVA_HOME && ls -l "$JAVA_HOME/bin"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Build
        run: ./gradlew --info --stacktrace build
      - name: JLink
        run: ./gradlew --info --stacktrace jlinkZip
      - name: JPackage
        run: ./gradlew --info --stacktrace jpackage
      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: dragonjars-${{matrix.os}}-exe
          path: build/jpackage/*.exe
          if-no-files-found: ignore
      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: dragonjars-${{matrix.os}}-deb
          path: build/jpackage/*.deb
          if-no-files-found: ignore
      - name: Upload RPM
        uses: actions/upload-artifact@v4
        with:
          name: dragonjars-${{matrix.os}}-rpm
          path: build/jpackage/*.rpm
          if-no-files-found: ignore
      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: dragonjars-${{matrix.os}}-zip
          path: build/distributions/*.zip
          if-no-files-found: ignore


